"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloNextAppProvider } from "@apollo/experimental-nextjs-app-support";
import { makeClient } from "@/config/apollo-client";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloNextAppProvider makeClient={makeClient}>
          {children}
        </ApolloNextAppProvider>
      </body>
    </html>
  );
}
